# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-06 06:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='song_duration',
            field=models.CharField(default='04:00', max_length=10),
            preserve_default=False,
        ),
    ]
