# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-18 14:38
from __future__ import unicode_literals

from django.db import migrations, models
import music.models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0009_album_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='album_logo',
            field=models.FileField(default=b'static/music/images/album_logos/default.jpg', upload_to=music.models.content_file_name),
        ),
        migrations.AlterField(
            model_name='song',
            name='audio_file',
            field=models.CharField(max_length=250),
        ),
    ]
