# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-25 09:22
from __future__ import unicode_literals

from django.db import migrations, models
import music.models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0013_auto_20160925_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='album_logo',
            field=models.FileField(blank=True, default='music\\static\\music\\images\x07lbum_logos\\default.jpg', null=True, upload_to=music.models.content_file_name),
        ),
    ]
