# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-08 07:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0018_auto_20160929_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='audio_file',
            field=models.FileField(blank=True, default='', upload_to=''),
        ),
    ]
